services:
  meeting_room_booking_system:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_service
      - redis_service
    ports:
      - 3000:3000
    networks:
      - backend_network

  mysql_service:
    image: mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: mysql_root_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - backend_network

  redis_service:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes --requirepass redis_password
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
